/* MISRA RULE 19.15 not violated: The QAC-Tool states a violation of rule 19.15 with
 * message 0883 below. Anyhow, there is a double include prevention and therefore,
 * the message is considered to be wrong. */
/* double include preventer */
#ifndef _TRUSTCFT_H      /* PRQA S 0883 EOF */ /* see MISRA comment above */
#define _TRUSTCFT_H
/* file: trustfct.h, automatically generated by gencanoe.exe, Version: 5.02 */
/* configuration read from: C:\Users\nituser\AppData\Local\Temp\Cfg_Gen-1678624980302-7\OsProxyFiles-1678626878311-0\Os_ActiveEcuC.arxml.oil */
/* generation at  : Sun Mar 12 14:14:39 2023 */
/* Unlimited license 1234567890 for CANoeEmu Generic License */
/* Implementation: CANoeOsekEmu */
/* Version of general code: 5.31 */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 2
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif



		/* Trusted functions not used in SC1*/

/* END OF C:\nit-au-03\PSZR_dimitrijevic_lazarevic\AUTOSAR_Exercises\AFS\Appl\GenDataVtt\trustfct.h */

#endif /* _TRUSTCFT_H double include preventer */
