/* file: trustfct.c, automatically generated by gencanoe.exe, Version: 5.02 */
/* configuration read from: C:\Users\nituser\AppData\Local\Temp\Cfg_Gen-1678624980302-7\OsProxyFiles-1678626878311-0\Os_ActiveEcuC.arxml.oil */
/* generation at  : Sun Mar 12 14:14:39 2023 */
/* Unlimited license 1234567890 for CANoeEmu Generic License */
/* Implementation: CANoeOsekEmu */
/* Version of general code: 5.31 */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 2
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "Os.h"
#else
 #include <Os.h>
#endif


/* END OF C:\nit-au-03\PSZR_dimitrijevic_lazarevic\AUTOSAR_Exercises\AFS\Appl\GenDataVtt\trustfct.c */

